/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Vanessa
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoMenuPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuConta = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuDespesa = new javax.swing.JMenuItem();
        jMenuReceita = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuMensal = new javax.swing.JMenuItem();
        jMenuAnual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFundoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-menu2.jpg"))); // NOI18N

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente-icon.png"))); // NOI18N
        jMenuConta.setText("Conta");
        jMenuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuConta);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");
        jMenuOperacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/despesa.png"))); // NOI18N
        jMenuDespesa.setText("Despesa");
        jMenuDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDespesaActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuDespesa);

        jMenuReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/receita.png"))); // NOI18N
        jMenuReceita.setText("Receita");
        jMenuReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReceitaActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuReceita);

        jMenuBar1.add(jMenuOperacao);

        jMenuRelatorio.setText("Relatório");
        jMenuRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuMensal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/calendar-mes.png"))); // NOI18N
        jMenuMensal.setText("Mensal");
        jMenuMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMensalActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuMensal);
        jMenuMensal.getAccessibleContext().setAccessibleName("");
        jMenuMensal.getAccessibleContext().setAccessibleDescription("");

        jMenuAnual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/calendarAno.png"))); // NOI18N
        jMenuAnual.setText("Anual");
        jMenuAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAnualActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuAnual);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFundoMenuPrincipal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFundoMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaActionPerformed
        CadastroConta conta = new CadastroConta();
        conta.show();
    }//GEN-LAST:event_jMenuContaActionPerformed

    private void jMenuMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMensalActionPerformed
        RelatorioMensal rm = new RelatorioMensal();
        rm.show();
    }//GEN-LAST:event_jMenuMensalActionPerformed

    private void jMenuAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAnualActionPerformed
        RelatorioAnual ra = new RelatorioAnual();
        ra.show();
    }//GEN-LAST:event_jMenuAnualActionPerformed

    private void jMenuDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDespesaActionPerformed
        Despesa d = new Despesa();
        d.show();
    }//GEN-LAST:event_jMenuDespesaActionPerformed

    private void jMenuReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReceitaActionPerformed
        Receita r = new Receita();
        r.show();
    }//GEN-LAST:event_jMenuReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoMenuPrincipal;
    private javax.swing.JMenuItem jMenuAnual;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuConta;
    private javax.swing.JMenuItem jMenuDespesa;
    private javax.swing.JMenuItem jMenuMensal;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenuItem jMenuReceita;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables
}
