/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.vanessa.financeiroPessoal.DAO.RegistroDAO;
import br.com.vanessa.financeiroPessoal.model.Registro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vanessa
 */
public class RelatorioAnual extends javax.swing.JFrame {
    private String tipo;

    /**
     * Creates new form RelatorioAnual
     */
    public RelatorioAnual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAno = new javax.swing.JTextField();
        todos = new java.awt.Checkbox();
        receita = new java.awt.Checkbox();
        despesa = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        BtnSair = new javax.swing.JButton();
        jTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        todos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        todos.setLabel("Todos");
        todos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                todosItemStateChanged(evt);
            }
        });
        getContentPane().add(todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, -1));

        receita.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        receita.setLabel("Receita");
        receita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                receitaItemStateChanged(evt);
            }
        });
        getContentPane().add(receita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, -1));

        despesa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        despesa.setLabel("Despesa");
        despesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                despesaItemStateChanged(evt);
            }
        });
        getContentPane().add(despesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 90, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor", "Parcela", "Desconto", "Valor da Parcela", "Tipo", "Data de Vencimento", "Data de Pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 860, 350));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/document.png"))); // NOI18N
        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 250, 50));

        BtnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, -1, -1));

        jTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Total:"));
        getContentPane().add(jTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ano:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/relatorioFundo.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       readJTable(RegistroDAO.pesquisarAnual(jAno.getText(),tipo));
         jTotal.setText(RegistroDAO.somarAno(jAno.getText(), tipo).toString());
       // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void receitaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_receitaItemStateChanged
        tipo = "'Receita'"; 
        todos.setState(false);
        despesa.setState(false);
    }//GEN-LAST:event_receitaItemStateChanged

    private void despesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_despesaItemStateChanged
        tipo = "'Despesa'";
        todos.setState(false);
        receita.setState(false);
    }//GEN-LAST:event_despesaItemStateChanged

    private void todosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_todosItemStateChanged
        tipo = "'Despesa', 'Receita'"; 
        despesa.setState(false);
        receita.setState(false);
    }//GEN-LAST:event_todosItemStateChanged

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnSairActionPerformed
    public void readJTable( List<Registro> lst) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        String [] cols = {"Descrição", "Valor", "Parcela", "Desconto", "Valor da Parcela", "Tipo", "Data de Vencimento", "Data de Pagamento"};
        modelo.setColumnIdentifiers(cols);
        modelo.setNumRows(0);
        
        for(Registro r :lst){
            modelo.addRow(new Object[]{
                r.getDescricao(),
                r.getValor(),
                r.getParcela(),
                r.getDesconto(),
                r.getValorParcela(),
                r.getTipo(),
                formatarData(r.getDataVencimento()),
                formatarData(r.getDataPagamento())
            });
       
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioAnual().setVisible(true);
            }
        });
    }
    
    private String formatarData(Calendar data) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        return dateFormat.format(data.getTime());
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSair;
    private java.awt.Checkbox despesa;
    private javax.swing.JTextField jAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jTotal;
    private java.awt.Checkbox receita;
    private java.awt.Checkbox todos;
    // End of variables declaration//GEN-END:variables
}
